live_config_reload = true

[font]
normal = { family = "iMWritingMono Nerd Font" }
size = 7

[shell]
program = "zsh"

[window]
decorations = "None"
dynamic_padding = true

[colors.selection]
text = "#2f2f2f"
background = "#fce3fc"

[colors.primary]
foreground = "#2f2f2f"
background = "#fff7f1"

[colors.normal]
black = "#2f2f2f"
red = "#ff4485"
green = "#56b356"
blue = "#002aff"
yellow = "#f728c0"
magenta = "#a600ff"
cyan = "#a600ff"
white = "#ffaaff"

[scrolling]
history = 100000

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
]
