#!/usr/bin/env bash

set -e

export NIXPKGS_ALLOW_UNFREE=1

nixos-rebuild build --flake ".#${HOST}" --impure "$@" --show-trace

nvd diff /run/current-system result

sudo NIXPKGS_ALLOW_UNFREE=1 nixos-rebuild switch --flake ".#${HOST}" --impure "$@"
